[Group 18] Requisito 11
tryber/sd-12-project-frontend-online-store pull request #517
Opened 2021-07-15 01:51 UTC by Gabriela-Guerra

2021-07-15 18:15 UTC, rslfilho requested changes

2021-07-15 18:15 UTC, rslfilho commented on src/components/FormEvaluator.js
> +    this.setState({ rating: event.target.value });
Interessante ter um state inicial para o rating também =D

2021-07-15 18:15 UTC, rslfilho commented on src/components/FormEvaluator.js
> +            onChange={ (event) => this.setState({ textArea: event.target.value }) }
Tentar usar o a mesma onChangeEmail para os dois campos do formulário, será se da?

2021-07-15 18:15 UTC, rslfilho commented on src/components/FormEvaluator.js
> +          onClick={ () => this.submitBtn }
Não precisa da arrow function aqui

2021-07-15 18:15 UTC, rslfilho commented on src/components/FormEvaluator.js
> +    if (localState === null) return null;
if (localState) this.setState(localState)

Dessa forma você só seta o localState se existir,  e não precisa desse return null, já que sua função não retorna nada. No caso apagaria a linha seguinte também..

2021-07-15 18:17 UTC, guilhermehjunior commented on src/components/FormEvaluator.js
> +    this.setState({ rating: event.target.value });
O rating nao tem um estado inicial, acho que seria interessante colocar um :+1:

2021-07-15 18:17 UTC, guilhermehjunior commented on src/components/FormEvaluator.js
> +          onClick={ () => this.submitBtn }
Nao precisa de uma arrow function, pode passar a this.submitBtn direto! :top:

2021-07-15 18:17 UTC, guilhermehjunior commented on src/components/FormEvaluator.js
> +            onChange={ (event) => this.setState({ textArea: event.target.value }) }
Acho que seria interessante utilizar uma única função para o onChange do textArea e do input. (se vc quiser, já temos um onChange genérico no APP, dá para usar ele) :cat:

2021-07-15 19:47 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +    this.setState({ rating: event.target.value });
Feito!

2021-07-15 19:47 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +            onChange={ (event) => this.setState({ textArea: event.target.value }) }
Feito!

2021-07-15 19:47 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +          onClick={ () => this.submitBtn }
Feito!

2021-07-15 19:47 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +    if (localState === null) return null;
Feito!

2021-07-15 19:47 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +    this.setState({ rating: event.target.value });
Feito!

2021-07-15 19:48 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +          onClick={ () => this.submitBtn }
Feito!

2021-07-15 19:50 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +            onChange={ (event) => this.setState({ textArea: event.target.value }) }
Aceitei a sugestão do Roberval e inseri o mesmo onChange do email no textArea. Obrigada pelo review! ; )

2021-07-15 20:23 UTC, rslfilho requested changes

2021-07-15 20:23 UTC, rslfilho commented on src/components/FormEvaluator.js
> +    this.setState({ email, textArea: event.target.value });
Coloca o código dessa função assim, que fica melhor e genérico 

handleChange({ target }) {
    const { name } = target;
    const value = target.type === 'checkbox' ? target.checked : target.value;

    this.setState({
      [name]: value,
    });
  }

2021-07-15 20:23 UTC, rslfilho commented on src/components/FormEvaluator.js
> +            type="email"
adicionar o atributo name="email" nesse input

2021-07-15 20:23 UTC, rslfilho commented on src/components/FormEvaluator.js
> +            data-testid="product-detail-evaluation"
adiciona o atributo name="textArea" nesse textarea

2021-07-15 21:23 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +    this.setState({ email, textArea: event.target.value });
Feito!

2021-07-15 21:23 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +            data-testid="product-detail-evaluation"
Feito!

2021-07-15 21:24 UTC, Gabriela-Guerra commented on src/components/FormEvaluator.js
> +            type="email"
Feito!

2021-07-16 11:52 UTC, rslfilho approved these changes

2021-07-16 11:54 UTC, felipelouzeiro approved these changes

2021-07-16 18:56 UTC, merged