Adiciona estilos na página de checkout
tryber/sd-12-project-frontend-online-store pull request #720
Opened 2021-07-19 15:21 UTC by Renansf8

2021-07-19 21:19 UTC, dihsantanna requested changes

2021-07-19 21:19 UTC, dihsantanna commented on src/components/checkout_form/components_form/InputAddress.jsx
> +import '../../../css/inputCheckout.css';
Fala Renan, não acha que ficaria mais simples se você importasse esse documento de css só no CheckoutForm?
Ou até mesmo pode migrar todo o css dos inputs para o checkoutForm.css. Como os inputs são filhos do CheckoutForm isso seria possível! 😃

2021-07-20 15:03 UTC, samuel-constantino commented on src/App.js
> +      cartItems: storage || [],
Muito boa essa ideia para não perder o carrinho, quando atualizar. Parabéns!

2021-07-20 15:05 UTC, samuel-constantino commented on src/App.js
> +    console.log(cartItems);
Esse console.log() foi usado apenas para Debug? Não seria mais interessante retirá-lo? :smile:

2021-07-23 03:49 UTC, dihsantanna approved these changes

2021-07-23 13:35 UTC, GabrielTakaki approved these changes

2021-07-23 13:35 UTC, merged